version: '3'

services:
  app:
    container_name: app-url
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ".:/opt/app"  
    depends_on:
      - mysql
      - redis
    networks:
      - app-net

  mysql:
    container_name: app-url-mysql
    image: mysql:8
    environment:
      - MYSQL_DATABASE=app-url
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=smd
      - MYSQL_PASSWORD=p@ssword
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-net
  redis:
    container_name: app-url-redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /tmp/redis:/data
    networks:
      - app-net  
volumes:
  dbdata:

networks:
  app-net:
    driver: bridge
